### ISSUE TITLE
Will I need a graphical environment and chrome to run on vps/vds?

### ISSUE THREAD

**Issue by devmitrandir** [acheong08/ChatGPT-Proxy#1]

**Comment by acheong08** [comment]
`xvfb`

**Comment by fred913** [comment]
It does, but it can be ran in a virtual graphical environment, such as xvfb as acheong08 mentioned above. To run the program with xvfb vge sandbox, run:
`xvfb-run python proxy.py`
In my Pull Request there's an implementation as a configurable option "virtualdisplay" which provides an integrated ability to automatically create a virtual graphical environment for that.

**Comment by x1cked** [comment]
Thanks guys
