### ISSUE TITLE
Who's IP is the one mentioned in the code?

### ISSUE THREAD

**Issue by abhisheksoni27** [acheong08/ChatGPT-Proxy#4]
185.199.229.156:7492

What is this about?

**Comment by acheong08** [comment]
My proxy

**Comment by acheong08** [comment]
It's IP authenticated so don't think about trying to hack it lol

**Comment by abhisheksoni27** [comment]
Hahaha, sure.

I am curious and want to understand what the proxy IP serves the purpose of. In the initial commits, it wasn't present.

What role does it play? What does it have to do with Cloudflare?

How can I host my own proxy server? What do I need? Could you please elaborate?

**Comment by abhisheksoni27** [comment]
Is it just a normal proxy/relay server?

**Comment by acheong08** [comment]
> Is it just a normal proxy/relay server?

Yes normal socks5

**Comment by abhisheksoni27** [comment]
Got it, thanks!
