### ISSUE TITLE
uvicorn and WsgiToAsgi variables are undefined

### ISSUE THREAD

**Issue by abhisheksoni27** [acheong08/ChatGPT-Proxy#6]
Getting Name Error

**Comment by fred913** [comment]
Without doubt, the code is now just broken after some force mergings. We'll fix it right soon (PR pending)

**Comment by JerryWn12** [comment]
Hi, what proxy address should I use in config.json? Can I use the localhost? What is the proxy address

**Comment by fred913** [comment]
> Hi, what proxy address should I use in config.json? Can I use the localhost? What is the proxy address

@JerryWn12 

It's up to you. If you have regular access to Cloudflare and ChatGPT, and you don't care if your IP address exposes, you can set it to null (in my branch) (PR is in pending so the code here is not latest yet).

**Comment by JerryWn12** [comment]
> > Hi, what proxy address should I use in config.json? Can I use the localhost? What is the proxy address
> 
> @JerryWn12
> 
> It's up to you. If you have regular access to Cloudflare and ChatGPT, and you don't care if your IP address exposes, you can set it to null (in my branch) (PR is in pending so the code here is not latest yet).

@fred913 Thank you ❤️

**Comment by fred913** [comment]
Solved.

**Comment by abhisheksoni27** [comment]
Awesome, thanks!
