### ISSUE TITLE
Unknown variable named PROXY

### ISSUE THREAD

**Issue by abhisheksoni27** [acheong08/ChatGPT-Proxy#7]
Should be selected from config. Also, how are we reading the config here?

**Comment by fred913** [comment]
Yeah, you're right. I don't know if there are something wrong merging my Pull Request forcely, but it SHOULD actually work if you check my original PR out. Now I created a new one, which fixes all those errors.

**Comment by fred913** [comment]
Solved.

**Comment by abhisheksoni27** [comment]
Thanks!
